version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 5
